server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/damianrein/Microservicios-Tutorial
          search-paths: config-data
  application:
    name: config-service            
